- name: "Creates directory"
  file:
    path: "~/server"
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "~/project/artifact.tar.gz"
    dest: "~/server/artifact.tar.gz"

- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "~/server/artifact.tar.gz"
    dest: "~/server"

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/server
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready
